# Generated by Django 3.0.7 on 2020-12-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201230_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='current_price',
            new_name='base_price',
        ),
    ]
