# Generated by Django 3.0.7 on 2020-12-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201230_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='current_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='base_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
