# Generated by Django 3.0.7 on 2020-12-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201230_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='closed_listing',
            field=models.BooleanField(default=False),
        ),
    ]
